@dms = http://localhost:4004
@catalog-service = {{dms}}/browse
# Lenovo Thinkpad T480
@deviceID = 101

### View current status on Lenovo Thinkpad T480
GET {{catalog-service}}/Devices({{deviceID}})

### Create an order for 7 instances of Lenovo Thinkpad T480
POST {{catalog-service}}/Orders
Content-Type: application/json

{ 
    "OrderNr":"1",
    "Items":[{
        "device_ID": {{deviceID}},
        "quantity": 7
    }]
}

### Create an order for a single instance of Lenovo Thinkpad T480
POST {{catalog-service}}/Orders
Content-Type: application/json

{ 
    "OrderNr":"2",
    "Items":[{
        "device_ID": {{deviceID}},
        "quantity": 1
    }]
}

### List all current devices in Russian locale
GET {{catalog-service}}/Devices?sap-language="ru"
